main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('webauth.urls', 'webauth')),
    path('', include('webapp.urls', 'webapp')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
    path('', MainPageView.as_view(), name='index'),
    path('food', FoodListView.as_view(), name='food_list'),
    path('food/<int:pk>', FoodDetailView.as_view(), name='food_detail'),
    path('food/<int:pk>/update', FoodUpdateView.as_view(), name='food_update'),
    path('food/<int:pk>/delete', FoodDeleteView.as_view(), name='food_delete'),
    path('food/create', FoodCreateView.as_view(), name='food_create'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('order/create', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/update', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/food/create', OrderFoodCreateView.as_view(), name='order_food_create'),
    path('order/<int:pk>/food/<int:food_pk>/delete', OrderFoodDeleteView.as_view(), name='order_food_delete'),
    path('order/<int:pk>/status', OrderDeliverView.as_view(), name='order_deliver'),
    path('order/<int:pk>/cancel', OrderRejectView.as_view(), name='order_cancel'),
]

webauth/urls.py
from django.urls import path
from webauth.views import *

app_name = 'webauth'

urlpatterns = [
    path('auth/login', login_view, name='login'),
    path('auth/logout', logout_view, name='logout')
]

webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='employee', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, verbose_name='Телефон')

    def __str__(self):
        return self.user.get_full_name()


class Food(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')
    photo = models.ImageField(verbose_name='Фотография')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_PREPARING = 'preparing'
    STATUS_ON_WAY = 'on_way'
    STATUS_DELIVERED = 'delivered'
    STATUS_CANCELED = 'canceled'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый'),
        (STATUS_PREPARING, 'Готовится'),
        (STATUS_ON_WAY, 'В пути'),
        (STATUS_DELIVERED, 'Доставлен'),
        (STATUS_CANCELED, 'Отменён')
    )

    contact_phone = models.CharField(max_length=50, verbose_name='Контактный телефон')
    contact_name = models.CharField(max_length=100, verbose_name='Имя клиента')
    delivery_address = models.CharField(max_length=200, null=True, blank=True, verbose_name='Адрес доставки')
    status = models.CharField(max_length=20, default=STATUS_NEW, verbose_name='Статус', choices=STATUS_CHOICES)
    operator = models.ForeignKey(User, null=True, blank=True, related_name='orders', verbose_name='Оператор', on_delete=models.PROTECT)
    courier = models.ForeignKey(User, null=True, blank=True, related_name='delivered', verbose_name='Курьер', on_delete=models.PROTECT)

    def __str__(self):
        return self.contact_phone

    @property
    def get_sum(self):
        order_sum = 0

        for food in self.foods.all():
            order_sum += food.amount * food.food.price
        return order_sum

    class Meta:
        permissions = [
            ('can_take_order', 'Can take and delivered order')
        ]



class OrderFood(models.Model):
    order = models.ForeignKey(Order, related_name='foods', verbose_name='Заказ', on_delete=models.PROTECT)
    food = models.ForeignKey(Food, related_name='+', verbose_name='Блюдо', on_delete=models.PROTECT)
    amount = models.IntegerField(verbose_name='Количество')

    def __str__(self):
        return str(self.food)


    @property
    def get_sum(self):
        order_sum = self.amount * self.food.price
        return order_sum

webapp/forms.py
from django import forms
from webapp.models import Food, Order, OrderFood


class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        exclude = []


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['operator', 'courier']


class OrderFoodForm(forms.ModelForm):
    class Meta:
        model = OrderFood
        exclude = ['order']

webapp/views.py
from django.views.generic import DetailView, CreateView, UpdateView, View, DeleteView, ListView
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseForbidden
from webapp.models import Food, Order, OrderFood
from webapp.forms import FoodForm, OrderForm, OrderFoodForm
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class MainPageView(LoginRequiredMixin, ListView):

    model = Order
    template_name = 'index.html'
    ordering = ['status']


class FoodListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'webapp.view_food'
    model = Food
    template_name = 'food_list.html'


class FoodDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'webapp.view_food'
    model = Food
    template_name = 'food_detail.html'


class FoodUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'webapp.change_food'
    model = Food
    template_name = 'food_update.html'
    form_class = FoodForm

    def get_success_url(self):
        return reverse('webapp:food_detail', kwargs={'pk': self.object.pk})


class FoodDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'webapp.delete_food'
    model = Food
    success_url = reverse_lazy('webapp:food_list')


class FoodCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'webapp.add_food'
    model = Food
    template_name = 'food_create.html'
    form_class = FoodForm

    def get_success_url(self):
        return reverse('webapp:food_detail', kwargs={'pk': self.object.pk})


class OrderDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'webapp.view_order'
    model = Order
    template_name = 'order_detail.html'


class OrderUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'webapp.change_order'
    model = Order
    template_name = 'order_update.html'
    form_class = OrderForm

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


class OrderDeliverView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'webapp.can_take_order'

    def get(self, *args, **kwargs):
            order = get_object_or_404(Order, pk=self.kwargs['pk'])
            print(order.status)
            if order.status == 'preparing':
                order.status = 'on_way'
                order.courier = self.request.user
            elif order.status == 'on_way' and order.courier == self.request.user:
                order.status = 'delivered'
                order.courier = self.request.user
            order.save()
            return redirect('webapp:index')


# классовое на базе DeleteView с выводом страницы подтверждения
class OrderRejectView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'webapp.delete_order'
    model = Order
    template_name = 'order_cancel.html'

    def get_success_url(self):
        return reverse('webapp:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()

        self.object.status = 'canceled'
        self.object.save()
        return HttpResponseRedirect(success_url)


# Представления для создания заказа
class OrderCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'webapp.add_order'
    model = Order
    template_name = 'order_create.html'
    form_class = OrderForm

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.operator = self.request.user
        form.save()
        return super(OrderCreateView, self).form_valid(form)



# ... и для добавления блюд в заказ
class OrderFoodCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'webapp.add_orderfood'
    model = OrderFood
    form_class = OrderFoodForm
    template_name = 'order_food_create.html'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = Order.objects.get(pk=self.kwargs.get('pk'))
        return context

    def form_valid(self, form):
        form.instance.order = get_object_or_404(Order, pk=self.kwargs['pk'])
        form.save()
        return super(OrderFoodCreateView, self).form_valid(form)


class OrderFoodDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'webapp.delete_orderfood'
    model = OrderFood
    template_name = 'order_food_delete.html'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = Order.objects.get(pk=self.kwargs.get('pk'))
        context['food'] = OrderFood.objects.get(pk=self.kwargs.get('food_pk'))
        return context

    def delete(self, request, *args, **kwargs):
        self.object = OrderFood.objects.get(pk=self.kwargs.get('food_pk'))
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

webapp/templates/_food_list.html
<td><img src="/uploads/{{ food.photo }}" alt="{{ food.name }}" class="food_list_img"></td>
<td>{{ food.name }}</td>
<td>{{ food.price }}</td>

webapp/templates/_order_list.html
<td>
{{ order.get_status_display }}
{% if perms.webapp.can_take_order %}
    {% if order.status == 'preparing' %}
        <p style="margin-top: 5px">
            <a class="btn btn-warning" href="{% url 'webapp:order_deliver' order.pk %}">Take order</a>
        </p>
    {% endif %}
    {% if order.status == 'on_way' %}
        <p style="margin-top: 5px">
            {% if order.courier == user %}
                <a class="btn btn-warning" href="{% url 'webapp:order_deliver' order.pk %}">Deliver</a>
            {% else %}
                <i style="color: #888888">delivery by</i><br> <b>{{ order.courier }}</b>
            {% endif %}
        </p>
    {% endif %}
{% endif %}

</td>
<td>{{ order.contact_name }}</td>
<td>{{ order.contact_phone }}</td>
<td>{{ order.delivery_address }}</td>
<td>
    {% for o in order.foods.all %}
        <b>{{ o }}: </b>{{ o.amount }} x <i>{{ o.food.price }}</i> = {{ o.get_sum }}
        {% if perms.webapp.delete_orderfood %}
             | <a class="delete_small" href="{% url 'webapp:order_food_delete' order.pk o.pk  %}">Delete</a>
        {% endif %}

        {% if not forloop.last %}<br> {% endif %}
    {% endfor %}
</td>
<td><b>{{ order.get_sum }}</b></td>

webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'webapp:index' %}">Orders</a></li>
                <li><a href="{% url 'webapp:food_list' %}">Food</a></li>

                {% if perms.webapp.add_food and perms.webapp.add_order %}
                    <li><a href="{% url 'webapp:food_create' %}">Add Food</a></li>
                    <li><a href="{% url 'webapp:order_create' %}">Add Order</a></li>
                {% endif %}

            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item navbar-text">Привет, {{ user.username }}!</li>
                    <li class="nav-item"><a href="{% url 'webauth:logout' %}" class="nav-link">Выход</a></li>
                    <li class="nav-item"><a href="{% url 'webapp:index' %}" class="nav-link">На главную</a></li>
                    {% block menu %}{% endblock %}
                {% else %}
                    <li class="nav-item"><a href="{% url 'webauth:login' %}" class="nav-link">Вход</a></li>
                {% endif %}
            </ul>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm-12">

            {% if user.is_authenticated %}

                {% block content %}{% endblock %}

            {% endif %}

        </div>
    </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
{#<script src="{% static 'js/popper.min.js' %}"></script>#}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

webapp/templates/food_create.html
{% extends 'base.html' %}
{% block title %}Add Food{% endblock %}
{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Add Food</div>
        <div class="panel-body">

            <form action="{% url 'webapp:food_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

        </div>
    </div>



{% endblock %}

webapp/templates/food_delete.html
{% extends 'base.html' %}
{% block title %}Food{% endblock %}
{% block content %}


    <div class="panel panel-primary">
        <div class="panel-heading">Food</div>
        <div class="panel-body">

        <img src="{{ food.photo.url }}" alt="Картинка еды">
        <h2>{{ food.name }}</h2>
        <h3>Price: {{ food.price }}</h3>
        <p>{{ food.description }}</p>

        <div class="line_helper"></div>

        <a href="{% url 'webapp:food_update' food.pk %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'webapp:food_update' food.pk %}" class="btn btn-danger">Delete</a>

        </div>
    </div>



{% endblock %}

{# Откройте /food/<pk>, чтобы посмотреть картинку еды на этой странице #}

webapp/templates/food_detail.html
{% extends 'base.html' %}
{% block title %}Food{% endblock %}
{% block content %}


    <div class="panel panel-primary">
        <div class="panel-heading">Food</div>
        <div class="panel-body">

        <img src="{{ food.photo.url }}" alt="Картинка еды">
        <h2>{{ food.name }}</h2>
        <h3>Price: {{ food.price }}</h3>
        <p>{{ food.description }}</p>


        {% if perms.webapp.change_food and perms.webapp.delete_food %}
            <div class="line_helper"></div>
            <a href="{% url 'webapp:food_update' food.pk %}" class="btn btn-primary">Edit</a>
            <a href="{% url 'webapp:food_delete' food.pk %}" class="btn btn-danger">Delete</a>
        {% endif %}

        </div>
    </div>



{% endblock %}

{# Откройте /food/<pk>, чтобы посмотреть картинку еды на этой странице #}

webapp/templates/food_list.html
{% extends 'base.html' %}

{% block title %}Food list{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Food list</div>
        <div class="panel-body">
        <table class="table table-striped">
        <thead>
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
        </thead>
            {% for food in food_list %}
                <tr>
                    {% include '_food_list.html' %}
                    <td>
                        <a href="{% url 'webapp:food_detail' food.pk %}" class="btn btn-success">View</a>
                        {% if perms.webapp.change_food and perms.webapp.delete_food %}
                            <a href="{% url 'webapp:food_update' food.pk %}" class="btn btn-primary">Edit</a>
                            <a href="{% url 'webapp:food_delete' food.pk %}" class="btn btn-danger">Delete</a>
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}
        </table>

        </div>
    </div>


{% endblock %}

webapp/templates/food_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Food{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Food Update</div>
        <div class="panel-body">

            <form action="{% url 'webapp:food_update' food.pk %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>


{% endblock %}

webapp/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Order list</div>
        <div class="panel-body">
        <table class="table table-striped">
        <thead>
            <tr>
                <th>Status</th>
                <th>Client</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Order info</th>
                <th>Total</th>
                <th>Actions</th>
            </tr>
        </thead>
            {% for order in order_list %}
                <tr>
                    {% include '_order_list.html' %}
                    {% if perms.webapp.change_order and perms.webapp.add_orderfood %}
                        <td><a href="{% url 'webapp:order_update' order.pk %}" class="btn btn-primary">Edit</a></td>
                        <td><a href="{% url 'webapp:order_food_create' order.pk %}" class="btn btn-success">Add food</a></td>
                    {% endif %}

                </tr>
            {% endfor %}
        </table>

        </div>
    </div>


{% endblock %}

webapp/templates/order_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Добавить заказ{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Order Create</div>
        <div class="panel-body">
            <form action="{% url 'webapp:order_create' %}" method="post">
                {% csrf_token %}
                {{ formset.media }}
                {{ form.as_p }}

                {% for form in formset %}
                    <hr>
                    <div class="ml-5">
                        {{ form.as_p }}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
        </div>
    </div>


{% endblock %}

{#{% block scripts %}#}
{#    <script src="{% static "dynamic_formsets/jquery.formset.js" %}" type="text/javascript"> </script>#}
{##}
{#    <script type="text/javascript">#}
{#        $('.order-food').formset();#}
{#    </script>#}
{#{% endblock %}#}

webapp/templates/order_detail.html
{% extends 'base.html' %}
{% block title %}Заказ{% endblock %}
{% block content %}

<div class="panel panel-primary">
        <div class="panel-heading">Order</div>
        <div class="panel-body">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Client</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>Order info</th>
                    <th>Total</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    {% include '_order_list.html' %}
                    <td>
                        <a href="{% url 'webapp:order_update' order.pk %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'webapp:order_food_create' order.pk %}" class="btn btn-success">Add food</a>
                    </td>
                </tr>
            </tbody>
        </table>



        </div>
    </div>

{% endblock %}

{# Откройте /order/<pk>, чтобы посмотреть список блюд для заказа на этой странице #}

webapp/templates/order_food_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Food to order{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Food</div>
        <div class="panel-body">

            {% if order.status == 'delivered' or order.status == 'on_way' %}
                <h2>Order already delivered or shipped</h2>
            {% else %}
                <form action="{% url 'webapp:order_food_create' order.pk %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            {% endif %}

        </div>
    </div>



{% endblock %}

webapp/templates/order_food_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add food to order{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Food</div>
        <div class="panel-body">

            {% if order.status == 'delivered' or order.status == 'on_way' %}
                <h2>Order already delivered or shipped</h2>
            {% else %}

               <h3>Are you sure to delete <i style="color:#888">{{ food }}*{{ food.amount }}</i> from order <i style="color:#888">"{{ order }}"</i>?</h3>
                    <form action="{% url 'webapp:order_food_delete' order.pk food.pk%}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
            {% endif %}

        </div>
    </div>



{% endblock %}

webapp/templates/order_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Добавить заказ{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Order Update</div>
        <div class="panel-body">
            {% if order.status == 'delivered' or order.status == 'on_way' %}
                <h2>Заказ уже доставляется или доставлен</h2>
            {% else %}
                <form action="{% url 'webapp:order_update' order.pk %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            {% endif %}
        </div>
    </div>


{% endblock %}